name: Oracle ARM Auto-Provision

on:
  schedule:
    - cron: '*/15 * * * *' # Ejecuta cada 15 minutos
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón

jobs:
  launch-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código
        uses: actions/checkout@v3

      - name: Instalar OCI CLI
        run: |
          python -m pip install --upgrade pip
          pip install oci-cli

      - name: Configurar credenciales de Oracle
        env:
              SUPPRESS_LABEL_WARNING: True
              CLAVE_PRIVADA: ${{ secrets.OCI_KEY_FILE }}
        run: |
              mkdir -p ~/.oci
              echo "[DEFAULT]" > ~/.oci/config
              echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
              echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
              echo "tenancy=${{ secrets.OCI_TENANT_OCID }}" >> ~/.oci/config
              echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
              echo "key_file=/home/runner/.oci/oci_api_key.pem" >> ~/.oci/config
              echo "$CLAVE_PRIVADA" > ~/.oci/oci_api_key.pem
              chmod 600 ~/.oci/oci_api_key.pem
              chmod 600 ~/.oci/config

      - name: Ejecutar Script de Lanzamiento
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: bash launch.sh
